name: api_rest_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  mongo_dart: ^0.10.3
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  meta: ^1.7.0
  shelf_cors_headers: ^0.1.5
  dart_jsonwebtoken: ^2.14.1
  get_it: ^8.0.2

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.2

assets:
  - .env